apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: asrworker
  name: asrworker-controller
spec:
  replicas: 2
  selector:
    name: asrworker
  template:
    metadata:
      labels:
        name: asrworker
    spec:
      containers:
      - image: gtrail/lucida:all
        command: ['/bin/bash', '-c']
        args: ['cd $LUCIDA_ROOT/speechrecognition/kaldi_gstreamer_asr/ && export GST_PLUGIN_PATH=$LUCIDA_ROOT/speechrecognition/kaldi_gstreamer_asr/kaldi/tools/gst-kaldi-nnet2-online/src && python kaldigstserver/worker.py -u ws://$ASRMASTER_PORT_8081_TCP_ADDR:8081/worker/ws/speech -c sample_english_nnet2.yaml']
        name: asrworker
