apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: we
  name: we-controller
spec:
  replicas: 1
  selector:
    name: we
  template:
    metadata:
      labels:
        name: we
    spec:
      containers:
      - image: gtrail/lucida:all
        command: ['/bin/sh', '-c']
        args: ['cd $LUCIDA_ROOT/weather/server/ && python WeatherServer.py']
        name: we
        ports:
        - containerPort: 8088
          name: thrift
        env:
          - name: WU_API_KEY
            valueFrom:
              secretKeyRef:
                name: apikeys
                key: wu-api-key
          - name: OWM_API_KEY
            valueFrom:
              secretKeyRef:
                name: apikeys
                key: owm-api-key
